server:
  port: 9095

spring:
  application:
    name: smart-volunteer-credit
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/smart_volunteer?useSSL=false&serverTimezone=UTC&characterEncoding=utf8
    username: userstest
    password: YOUR_DB_PASSWORD
  data:
    redis:
      host: localhost
      port: 6379
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848

mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true

rocketmq:
  name-server: localhost:9876
  consumer:
    group: credit-consumer-group
    topics: activity-checkin-topic;activity-complete-topic
